services:
  app:
    build:
      context: .
      image: machines/filestash:latest
    container_name: filestash
    restart: always
    environment:
    - APPLICATION_URL=
    - CANARY=true
    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/
    - /mnt/largepool:/data
    - /mnt/smallpool/files:/data/test

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    security_opt:
    - seccomp:unconfined
    environment:
    - JWT_ENABLED=false
    - ALLOW_PRIVATE_IP_ADDRESS=true
    - ALLOW_META_IP_ADDRESS=true
    volumes:
    - /usr/share/fonts:/usr/share/fonts

volumes:
    filestash: {}